name: Validate pull request

on: pull_request

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm i
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build
